spring.application.name=SmartPost

# PostgresSQL Database Configuration
spring.datasource.url = jdbc:postgresql://localhost:5433/smartpost
spring.datasource.username = postgres
spring.datasource.password = omp12
spring.datasource.driver-class-name = org.postgresql.Driver

# JPA/Hibernate Config
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

server.port= 8080

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

jwt.secret=JwLSB7NNc7euo/IKJfqakN5ps6YluQrK4ZT3rynL2OI=
jwt.expiration=86400000
jwt.refresh=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=comp.dmce12@gmail.com
spring.mail.password=paumaicyddaagaym
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend_url=https://api.smartpost.fun

smartpost.prediction.base-url=http://localhost:8000
smartpost.prediction.predict-path=/api/time-slot/predict
smartpost.prediction.connect-timeout-ms=2000
smartpost.prediction.read-timeout-ms=5000

smartpost.geocoding.base-url=https://nominatim.openstreetmap.org
smartpost.geocoding.user-agent=smartpost/1.0
smartpost.geocoding.connect-timeout-ms=2000
smartpost.geocoding.read-timeout-ms=5000

smartpost.superadmin.full-name=System Super Admin
smartpost.superadmin.username=superadmin
smartpost.superadmin.email=superadmin@smartpost.local
smartpost.superadmin.mobile-no=9999999999
smartpost.superadmin.password=superadmin123

# Magic Link Configuration
app.magic-link.secret=smartpost_super_secret_magic_link_key_2026_om_patil
app.magic-link.expiration-ms=28800000

twilio.account_sid=AC7b3bc3aa9a91d85bc83590dea6e323bc
twilio.auth_token=552e3558d92b2b7a0fc073af23a52dc2
twilio.service_sid=VA29d3dcb92cd725c2e80b2d8819504b70
twilio.sms_service_sid=MGc27d60c44fbcb720a6aabd5395f18b6a
twilio.virtual_number=+12139315789

firebase.config.path=firebase/firebase-service-account.json
google.maps.api-key=AIzaSyDq_0QcmQs5s8g5-7cWTDCQ-HHmRbXBZ8w
