spring.application.name=SmartPost

# PostgresSQL Database Configuration
spring.datasource.url = jdbc:postgresql://localhost:5433/smartpost
spring.datasource.username = postgres
spring.datasource.password =${DB_PASSWORD}
spring.datasource.driver-class-name = org.postgresql.Driver

# JPA/Hibernate Config
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

server.port= 8080

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRY}
jwt.refresh=${JWT_REFRESH}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_EMAIL}
spring.mail.password=${SMTP_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend_url=https://api.smartpost.fun

smartpost.prediction.base-url=http://localhost:8000
smartpost.prediction.predict-path=/api/time-slot/predict
smartpost.prediction.connect-timeout-ms=2000
smartpost.prediction.read-timeout-ms=5000

smartpost.geocoding.base-url=https://nominatim.openstreetmap.org
smartpost.geocoding.user-agent=smartpost/1.0
smartpost.geocoding.connect-timeout-ms=2000
smartpost.geocoding.read-timeout-ms=5000

smartpost.superadmin.full-name=${SYSTEM_ADMIN_NAME}
smartpost.superadmin.username=${SYSTEM_ADMIN_USERNAME}
smartpost.superadmin.email=${SYSTEM_ADMIN_EMAIL}
smartpost.superadmin.mobile-no=${SYSTEM_ADMIN_MOBILE}
smartpost.superadmin.password=${SYSTEM_ADMIN_PASSWORD}

# Magic Link Configuration
app.magic-link.secret=${MAGIC_LINK_SECRET}
app.magic-link.expiration-ms=28800000

twilio.account_sid=${TWILIO_ACCOUNT_SID}
twilio.auth_token=${TWILIO_AUTH_TOKEN}
twilio.service_sid=${TWILIO_SERVICE_SID}
twilio.sms_service_sid=${TWILIO_SMS_SERVICE_SID}
twilio.virtual_number=${TWILIO_VIRTUAL_MOBILE_NO}

firebase.config.path=${SERVICE_JSON_PATH}
google.maps.api-key=${GOOGLE_CLOUD_API_KEY}


